### ISSUE TITLE
Is there a easier way to locate whether or not a newly added func's test case is passed?

### ISSUE THREAD

**Issue by Fullstop000** [tikv/copr-test#17]
The output of all tests is a little verbose. And it's hard to find the corresponding test case result for a newly added function.

**Comment by breeswish** [comment]
Did you tried with latest master? It only output failed SQLs.

**Comment by Fullstop000** [comment]
It's weird that almost all the test cases fail in my local env 😂 while I just use the master branch of `tikv`, `tidb`, `pd` and `copr-test`.

```
2019/11/08 17:32:34 Test summary: non-matching queries: 24, success queries: 964, skipped queries: 36
2019/11/08 17:32:34 Test summary: Test case FAIL
2019/11/08 17:32:34 All test finished: pass cases: 1, fail cases: 15
+ Test finished
  - ./bin/push_down_test_bin exit code is 2
```

**Comment by breeswish** [comment]
What are failed tests?

**Comment by breeswish** [comment]
Could you try with current latest TiDB and TiKV?

**Comment by Fullstop000** [comment]
Close since it works fine in the lastest version now.
